services:
  - type: web
    name: casesolve-bot
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN_BOT
        sync: false
      - key: RENDER_URL
        sync: false
    disk:
      name: casesolve-data
      mountPath: /var/data
      sizeGB: 1
